# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainDesign.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1280, 720)
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 1280))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(16)
        font.setItalic(False)
        MainWindow.setFont(font)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout_2 = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(320, 0))
        self.frame.setMaximumSize(QtCore.QSize(250, 16777215))
        self.frame.setStyleSheet(_fromUtf8(""))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_9 = QtGui.QGridLayout(self.frame)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.tabWidget = QtGui.QTabWidget(self.frame)
        self.tabWidget.setMaximumSize(QtCore.QSize(320, 16777215))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.tabWidget.setFont(font)
        self.tabWidget.setStyleSheet(_fromUtf8("QGroupBox{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QToolButton{\n"
"background-color:transparent;\n"
"border:none;\n"
"}\n"
"\n"
"QToolButton:hover{\n"
"border-width: 2px;\n"
"background-color:qlineargradient(spread:pad, x1:0.965, y1:0.04, x2:0.975773, y2:1, stop:0 rgba(214, 225, 239, 255));\n"
"\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"background-color:rgb(193,210,238);\n"
"border-width: 1px;\n"
"border-color:rgb(5, 54, 118);\n"
"border-style: solid;\n"
"}\n"
"\n"
"QTabWidget{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QToolButton:checked{\n"
"background-color:rgb(193,210,238);\n"
"border-width: 1px;\n"
"border-color:rgb(5, 54, 118);\n"
"border-style: solid;\n"
"\n"
"}\n"
"\n"
"#QWidget#baselayer{\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"QWidget#vl_qwt_ProcessImgView{\n"
"border-width: 0.5px;\n"
"border-color:rgb(255, 85, 0);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"QWidget#controlBox{\n"
"border-width: 0.5px;\n"
"border-color:rgb(85, 170, 0);\n"
"border-style: solid;\n"
"border-radius:3px;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"QGroupBox{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"\n"
"\n"
"QTabWidget::pane { \n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:transparent;\n"
"\n"
"}\n"
"\n"
"QTabBar {\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:transparent;\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"background-color:transparent;\n"
"color:rgb(255, 0, 0);\n"
"}\n"
"QTabBar::tab:unselected{\n"
"background-color:transparent;\n"
"}"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.Objects = QtGui.QWidget()
        self.Objects.setObjectName(_fromUtf8("Objects"))
        self.gridLayout_16 = QtGui.QGridLayout(self.Objects)
        self.gridLayout_16.setMargin(0)
        self.gridLayout_16.setObjectName(_fromUtf8("gridLayout_16"))
        self.gp_object_tools = QtGui.QGroupBox(self.Objects)
        self.gp_object_tools.setMinimumSize(QtCore.QSize(280, 150))
        self.gp_object_tools.setMaximumSize(QtCore.QSize(16777215, 150))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gp_object_tools.setFont(font)
        self.gp_object_tools.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gp_object_tools.setObjectName(_fromUtf8("gp_object_tools"))
        self.btn_login = QtGui.QToolButton(self.gp_object_tools)
        self.btn_login.setGeometry(QtCore.QRect(160, 50, 71, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(14)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btn_login.setFont(font)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8("../resources/icons/hand_stop.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_login.setIcon(icon)
        self.btn_login.setIconSize(QtCore.QSize(32, 32))
        self.btn_login.setCheckable(True)
        self.btn_login.setAutoExclusive(False)
        self.btn_login.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btn_login.setObjectName(_fromUtf8("btn_login"))
        self.btn_inspect = QtGui.QPushButton(self.gp_object_tools)
        self.btn_inspect.setGeometry(QtCore.QRect(20, 60, 97, 27))
        self.btn_inspect.setObjectName(_fromUtf8("btn_inspect"))
        self.gridLayout_16.addWidget(self.gp_object_tools, 0, 0, 1, 1)
        self.gp_object_specification = QtGui.QGroupBox(self.Objects)
        self.gp_object_specification.setEnabled(True)
        self.gp_object_specification.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gp_object_specification.setFont(font)
        self.gp_object_specification.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gp_object_specification.setObjectName(_fromUtf8("gp_object_specification"))
        self.btnReset = QtGui.QToolButton(self.gp_object_specification)
        self.btnReset.setGeometry(QtCore.QRect(200, 20, 41, 71))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnReset.setFont(font)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/reset.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReset.setIcon(icon1)
        self.btnReset.setIconSize(QtCore.QSize(64, 64))
        self.btnReset.setCheckable(False)
        self.btnReset.setAutoExclusive(True)
        self.btnReset.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnReset.setObjectName(_fromUtf8("btnReset"))
        self.btnBackup = QtGui.QToolButton(self.gp_object_specification)
        self.btnBackup.setGeometry(QtCore.QRect(20, 30, 61, 61))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnBackup.setFont(font)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Backup-Sync-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnBackup.setIcon(icon2)
        self.btnBackup.setIconSize(QtCore.QSize(64, 64))
        self.btnBackup.setCheckable(False)
        self.btnBackup.setAutoExclusive(False)
        self.btnBackup.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnBackup.setObjectName(_fromUtf8("btnBackup"))
        self.btnReload = QtGui.QToolButton(self.gp_object_specification)
        self.btnReload.setGeometry(QtCore.QRect(100, 20, 71, 81))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnReload.setFont(font)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Reload icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnReload.setIcon(icon3)
        self.btnReload.setIconSize(QtCore.QSize(64, 64))
        self.btnReload.setCheckable(False)
        self.btnReload.setAutoExclusive(False)
        self.btnReload.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnReload.setObjectName(_fromUtf8("btnReload"))
        self.gp_object_specification_2 = QtGui.QGroupBox(self.gp_object_specification)
        self.gp_object_specification_2.setEnabled(True)
        self.gp_object_specification_2.setGeometry(QtCore.QRect(20, 130, 241, 321))
        self.gp_object_specification_2.setMinimumSize(QtCore.QSize(100, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gp_object_specification_2.setFont(font)
        self.gp_object_specification_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gp_object_specification_2.setObjectName(_fromUtf8("gp_object_specification_2"))
        self.val_rhs = QtGui.QLabel(self.gp_object_specification_2)
        self.val_rhs.setGeometry(QtCore.QRect(90, 60, 111, 41))
        self.val_rhs.setFrameShape(QtGui.QFrame.StyledPanel)
        self.val_rhs.setFrameShadow(QtGui.QFrame.Sunken)
        self.val_rhs.setText(_fromUtf8(""))
        self.val_rhs.setObjectName(_fromUtf8("val_rhs"))
        self.lbrhs = QtGui.QLabel(self.gp_object_specification_2)
        self.lbrhs.setGeometry(QtCore.QRect(30, 70, 66, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbrhs.setFont(font)
        self.lbrhs.setObjectName(_fromUtf8("lbrhs"))
        self.val_mdl = QtGui.QLabel(self.gp_object_specification_2)
        self.val_mdl.setGeometry(QtCore.QRect(90, 150, 111, 41))
        self.val_mdl.setFrameShape(QtGui.QFrame.StyledPanel)
        self.val_mdl.setFrameShadow(QtGui.QFrame.Sunken)
        self.val_mdl.setText(_fromUtf8(""))
        self.val_mdl.setObjectName(_fromUtf8("val_mdl"))
        self.lbmdl = QtGui.QLabel(self.gp_object_specification_2)
        self.lbmdl.setGeometry(QtCore.QRect(30, 160, 66, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbmdl.setFont(font)
        self.lbmdl.setObjectName(_fromUtf8("lbmdl"))
        self.val_lhs = QtGui.QLabel(self.gp_object_specification_2)
        self.val_lhs.setGeometry(QtCore.QRect(90, 230, 111, 41))
        self.val_lhs.setFrameShape(QtGui.QFrame.StyledPanel)
        self.val_lhs.setFrameShadow(QtGui.QFrame.Sunken)
        self.val_lhs.setText(_fromUtf8(""))
        self.val_lhs.setObjectName(_fromUtf8("val_lhs"))
        self.lblhs = QtGui.QLabel(self.gp_object_specification_2)
        self.lblhs.setGeometry(QtCore.QRect(30, 240, 66, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lblhs.setFont(font)
        self.lblhs.setObjectName(_fromUtf8("lblhs"))
        self.gridLayout_16.addWidget(self.gp_object_specification, 1, 0, 1, 1)
        self.tabWidget.addTab(self.Objects, _fromUtf8(""))
        self.Settings = QtGui.QWidget()
        self.Settings.setObjectName(_fromUtf8("Settings"))
        self.gridLayout_14 = QtGui.QGridLayout(self.Settings)
        self.gridLayout_14.setMargin(0)
        self.gridLayout_14.setObjectName(_fromUtf8("gridLayout_14"))
        self.groupBox = QtGui.QGroupBox(self.Settings)
        self.groupBox.setMinimumSize(QtCore.QSize(0, 250))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gpCameraTools = QtGui.QGroupBox(self.groupBox)
        self.gpCameraTools.setGeometry(QtCore.QRect(20, 20, 171, 171))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gpCameraTools.setFont(font)
        self.gpCameraTools.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gpCameraTools.setObjectName(_fromUtf8("gpCameraTools"))
        self.btnCam_0 = QtGui.QToolButton(self.gpCameraTools)
        self.btnCam_0.setGeometry(QtCore.QRect(10, 20, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnCam_0.setFont(font)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/camera.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnCam_0.setIcon(icon4)
        self.btnCam_0.setCheckable(True)
        self.btnCam_0.setChecked(True)
        self.btnCam_0.setAutoExclusive(True)
        self.btnCam_0.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnCam_0.setObjectName(_fromUtf8("btnCam_0"))
        self.btnCam_1 = QtGui.QToolButton(self.gpCameraTools)
        self.btnCam_1.setGeometry(QtCore.QRect(10, 70, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnCam_1.setFont(font)
        self.btnCam_1.setIcon(icon4)
        self.btnCam_1.setCheckable(True)
        self.btnCam_1.setAutoExclusive(True)
        self.btnCam_1.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnCam_1.setObjectName(_fromUtf8("btnCam_1"))
        self.btnCam_2 = QtGui.QToolButton(self.gpCameraTools)
        self.btnCam_2.setGeometry(QtCore.QRect(10, 110, 141, 31))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnCam_2.setFont(font)
        self.btnCam_2.setIcon(icon4)
        self.btnCam_2.setCheckable(True)
        self.btnCam_2.setAutoExclusive(True)
        self.btnCam_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.btnCam_2.setObjectName(_fromUtf8("btnCam_2"))
        self.swParameter = QtGui.QStackedWidget(self.groupBox)
        self.swParameter.setGeometry(QtCore.QRect(0, 320, 271, 301))
        self.swParameter.setObjectName(_fromUtf8("swParameter"))
        self.parm_cam_0 = QtGui.QWidget()
        self.parm_cam_0.setObjectName(_fromUtf8("parm_cam_0"))
        self.gridLayout_11 = QtGui.QGridLayout(self.parm_cam_0)
        self.gridLayout_11.setMargin(0)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.saCam_0 = QtGui.QScrollArea(self.parm_cam_0)
        self.saCam_0.setWidgetResizable(True)
        self.saCam_0.setObjectName(_fromUtf8("saCam_0"))
        self.sawcsCam_0 = QtGui.QWidget()
        self.sawcsCam_0.setGeometry(QtCore.QRect(0, 0, 238, 118))
        self.sawcsCam_0.setObjectName(_fromUtf8("sawcsCam_0"))
        self.gridLayout_8 = QtGui.QGridLayout(self.sawcsCam_0)
        self.gridLayout_8.setMargin(0)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.fmCamSample_0 = QtGui.QFrame(self.sawcsCam_0)
        self.fmCamSample_0.setMinimumSize(QtCore.QSize(220, 100))
        self.fmCamSample_0.setMaximumSize(QtCore.QSize(220, 100))
        self.fmCamSample_0.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fmCamSample_0.setFrameShadow(QtGui.QFrame.Raised)
        self.fmCamSample_0.setObjectName(_fromUtf8("fmCamSample_0"))
        self.hsCamSample_0 = QtGui.QSlider(self.fmCamSample_0)
        self.hsCamSample_0.setGeometry(QtCore.QRect(20, 20, 181, 29))
        self.hsCamSample_0.setOrientation(QtCore.Qt.Horizontal)
        self.hsCamSample_0.setObjectName(_fromUtf8("hsCamSample_0"))
        self.lbCamSample_0 = QtGui.QLabel(self.fmCamSample_0)
        self.lbCamSample_0.setGeometry(QtCore.QRect(30, 60, 171, 31))
        self.lbCamSample_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCamSample_0.setObjectName(_fromUtf8("lbCamSample_0"))
        self.gridLayout_8.addWidget(self.fmCamSample_0, 0, 0, 1, 1)
        self.saCam_0.setWidget(self.sawcsCam_0)
        self.gridLayout_11.addWidget(self.saCam_0, 1, 0, 1, 1)
        self.gpSourceTools_0 = QtGui.QGroupBox(self.parm_cam_0)
        self.gpSourceTools_0.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gpSourceTools_0.setFont(font)
        self.gpSourceTools_0.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gpSourceTools_0.setObjectName(_fromUtf8("gpSourceTools_0"))
        self.btnRecord_3 = QtGui.QToolButton(self.gpSourceTools_0)
        self.btnRecord_3.setGeometry(QtCore.QRect(160, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnRecord_3.setFont(font)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Actions-media-record-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnRecord_3.setIcon(icon5)
        self.btnRecord_3.setIconSize(QtCore.QSize(12, 12))
        self.btnRecord_3.setCheckable(True)
        self.btnRecord_3.setAutoExclusive(True)
        self.btnRecord_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnRecord_3.setObjectName(_fromUtf8("btnRecord_3"))
        self.btnLive_3 = QtGui.QToolButton(self.gpSourceTools_0)
        self.btnLive_3.setGeometry(QtCore.QRect(100, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnLive_3.setFont(font)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/Pause-Normal-Red-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnLive_3.setIcon(icon6)
        self.btnLive_3.setIconSize(QtCore.QSize(12, 12))
        self.btnLive_3.setCheckable(True)
        self.btnLive_3.setChecked(False)
        self.btnLive_3.setAutoExclusive(True)
        self.btnLive_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnLive_3.setObjectName(_fromUtf8("btnLive_3"))
        self.btnVideo_3 = QtGui.QToolButton(self.gpSourceTools_0)
        self.btnVideo_3.setGeometry(QtCore.QRect(30, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnVideo_3.setFont(font)
        icon7 = QtGui.QIcon()
        icon7.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/play-movies-icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnVideo_3.setIcon(icon7)
        self.btnVideo_3.setIconSize(QtCore.QSize(12, 12))
        self.btnVideo_3.setCheckable(True)
        self.btnVideo_3.setAutoExclusive(True)
        self.btnVideo_3.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnVideo_3.setObjectName(_fromUtf8("btnVideo_3"))
        self.gridLayout_11.addWidget(self.gpSourceTools_0, 0, 0, 1, 1)
        self.swParameter.addWidget(self.parm_cam_0)
        self.parm_cam_1 = QtGui.QWidget()
        self.parm_cam_1.setObjectName(_fromUtf8("parm_cam_1"))
        self.gridLayout_12 = QtGui.QGridLayout(self.parm_cam_1)
        self.gridLayout_12.setMargin(0)
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.gpSourceTools_1 = QtGui.QGroupBox(self.parm_cam_1)
        self.gpSourceTools_1.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gpSourceTools_1.setFont(font)
        self.gpSourceTools_1.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gpSourceTools_1.setObjectName(_fromUtf8("gpSourceTools_1"))
        self.btnRecord_4 = QtGui.QToolButton(self.gpSourceTools_1)
        self.btnRecord_4.setGeometry(QtCore.QRect(160, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnRecord_4.setFont(font)
        self.btnRecord_4.setIcon(icon5)
        self.btnRecord_4.setIconSize(QtCore.QSize(12, 12))
        self.btnRecord_4.setCheckable(True)
        self.btnRecord_4.setAutoExclusive(True)
        self.btnRecord_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnRecord_4.setObjectName(_fromUtf8("btnRecord_4"))
        self.btnLive_4 = QtGui.QToolButton(self.gpSourceTools_1)
        self.btnLive_4.setGeometry(QtCore.QRect(100, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnLive_4.setFont(font)
        self.btnLive_4.setIcon(icon6)
        self.btnLive_4.setIconSize(QtCore.QSize(12, 12))
        self.btnLive_4.setCheckable(True)
        self.btnLive_4.setChecked(False)
        self.btnLive_4.setAutoExclusive(True)
        self.btnLive_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnLive_4.setObjectName(_fromUtf8("btnLive_4"))
        self.btnVideo_4 = QtGui.QToolButton(self.gpSourceTools_1)
        self.btnVideo_4.setGeometry(QtCore.QRect(30, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnVideo_4.setFont(font)
        self.btnVideo_4.setIcon(icon7)
        self.btnVideo_4.setIconSize(QtCore.QSize(12, 12))
        self.btnVideo_4.setCheckable(True)
        self.btnVideo_4.setAutoExclusive(True)
        self.btnVideo_4.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnVideo_4.setObjectName(_fromUtf8("btnVideo_4"))
        self.gridLayout_12.addWidget(self.gpSourceTools_1, 0, 0, 1, 1)
        self.saCam_1 = QtGui.QScrollArea(self.parm_cam_1)
        self.saCam_1.setWidgetResizable(True)
        self.saCam_1.setObjectName(_fromUtf8("saCam_1"))
        self.sawcsCam_1 = QtGui.QWidget()
        self.sawcsCam_1.setGeometry(QtCore.QRect(0, 0, 238, 118))
        self.sawcsCam_1.setObjectName(_fromUtf8("sawcsCam_1"))
        self.gl_setting_cam_1 = QtGui.QGridLayout(self.sawcsCam_1)
        self.gl_setting_cam_1.setMargin(0)
        self.gl_setting_cam_1.setObjectName(_fromUtf8("gl_setting_cam_1"))
        self.fmCamSample_1 = QtGui.QFrame(self.sawcsCam_1)
        self.fmCamSample_1.setMinimumSize(QtCore.QSize(220, 100))
        self.fmCamSample_1.setMaximumSize(QtCore.QSize(220, 100))
        self.fmCamSample_1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fmCamSample_1.setFrameShadow(QtGui.QFrame.Raised)
        self.fmCamSample_1.setObjectName(_fromUtf8("fmCamSample_1"))
        self.hsCamSample_1 = QtGui.QSlider(self.fmCamSample_1)
        self.hsCamSample_1.setGeometry(QtCore.QRect(20, 20, 181, 29))
        self.hsCamSample_1.setOrientation(QtCore.Qt.Horizontal)
        self.hsCamSample_1.setObjectName(_fromUtf8("hsCamSample_1"))
        self.lbCamSample_1 = QtGui.QLabel(self.fmCamSample_1)
        self.lbCamSample_1.setGeometry(QtCore.QRect(30, 60, 171, 31))
        self.lbCamSample_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCamSample_1.setObjectName(_fromUtf8("lbCamSample_1"))
        self.gl_setting_cam_1.addWidget(self.fmCamSample_1, 1, 0, 1, 1)
        self.saCam_1.setWidget(self.sawcsCam_1)
        self.gridLayout_12.addWidget(self.saCam_1, 1, 0, 1, 1)
        self.swParameter.addWidget(self.parm_cam_1)
        self.parm_cam_2 = QtGui.QWidget()
        self.parm_cam_2.setObjectName(_fromUtf8("parm_cam_2"))
        self.gridLayout_13 = QtGui.QGridLayout(self.parm_cam_2)
        self.gridLayout_13.setMargin(0)
        self.gridLayout_13.setObjectName(_fromUtf8("gridLayout_13"))
        self.saCam_2 = QtGui.QScrollArea(self.parm_cam_2)
        self.saCam_2.setWidgetResizable(True)
        self.saCam_2.setObjectName(_fromUtf8("saCam_2"))
        self.sawcsCam_2 = QtGui.QWidget()
        self.sawcsCam_2.setGeometry(QtCore.QRect(0, 0, 251, 175))
        self.sawcsCam_2.setObjectName(_fromUtf8("sawcsCam_2"))
        self.gridLayout_10 = QtGui.QGridLayout(self.sawcsCam_2)
        self.gridLayout_10.setMargin(0)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.fmCamSample_2 = QtGui.QFrame(self.sawcsCam_2)
        self.fmCamSample_2.setMinimumSize(QtCore.QSize(220, 100))
        self.fmCamSample_2.setMaximumSize(QtCore.QSize(220, 100))
        self.fmCamSample_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.fmCamSample_2.setFrameShadow(QtGui.QFrame.Raised)
        self.fmCamSample_2.setObjectName(_fromUtf8("fmCamSample_2"))
        self.hsCamSample_2 = QtGui.QSlider(self.fmCamSample_2)
        self.hsCamSample_2.setGeometry(QtCore.QRect(20, 20, 181, 29))
        self.hsCamSample_2.setOrientation(QtCore.Qt.Horizontal)
        self.hsCamSample_2.setObjectName(_fromUtf8("hsCamSample_2"))
        self.lbCamSample_2 = QtGui.QLabel(self.fmCamSample_2)
        self.lbCamSample_2.setGeometry(QtCore.QRect(30, 60, 171, 31))
        self.lbCamSample_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCamSample_2.setObjectName(_fromUtf8("lbCamSample_2"))
        self.gridLayout_10.addWidget(self.fmCamSample_2, 2, 0, 1, 1)
        self.saCam_2.setWidget(self.sawcsCam_2)
        self.gridLayout_13.addWidget(self.saCam_2, 1, 0, 1, 1)
        self.gpSourceTools_2 = QtGui.QGroupBox(self.parm_cam_2)
        self.gpSourceTools_2.setMinimumSize(QtCore.QSize(0, 100))
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(True)
        font.setWeight(75)
        self.gpSourceTools_2.setFont(font)
        self.gpSourceTools_2.setAlignment(QtCore.Qt.AlignHCenter|QtCore.Qt.AlignTop)
        self.gpSourceTools_2.setObjectName(_fromUtf8("gpSourceTools_2"))
        self.btnVideo_2 = QtGui.QToolButton(self.gpSourceTools_2)
        self.btnVideo_2.setGeometry(QtCore.QRect(30, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnVideo_2.setFont(font)
        self.btnVideo_2.setIcon(icon7)
        self.btnVideo_2.setIconSize(QtCore.QSize(12, 12))
        self.btnVideo_2.setCheckable(True)
        self.btnVideo_2.setAutoExclusive(True)
        self.btnVideo_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnVideo_2.setObjectName(_fromUtf8("btnVideo_2"))
        self.btnRecord_2 = QtGui.QToolButton(self.gpSourceTools_2)
        self.btnRecord_2.setGeometry(QtCore.QRect(160, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnRecord_2.setFont(font)
        self.btnRecord_2.setIcon(icon5)
        self.btnRecord_2.setIconSize(QtCore.QSize(12, 12))
        self.btnRecord_2.setCheckable(True)
        self.btnRecord_2.setAutoExclusive(True)
        self.btnRecord_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnRecord_2.setObjectName(_fromUtf8("btnRecord_2"))
        self.btnLive_2 = QtGui.QToolButton(self.gpSourceTools_2)
        self.btnLive_2.setGeometry(QtCore.QRect(100, 30, 41, 41))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(True)
        font.setWeight(50)
        self.btnLive_2.setFont(font)
        self.btnLive_2.setIcon(icon6)
        self.btnLive_2.setIconSize(QtCore.QSize(12, 12))
        self.btnLive_2.setCheckable(True)
        self.btnLive_2.setChecked(False)
        self.btnLive_2.setAutoExclusive(True)
        self.btnLive_2.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnLive_2.setObjectName(_fromUtf8("btnLive_2"))
        self.gridLayout_13.addWidget(self.gpSourceTools_2, 0, 0, 1, 1)
        self.swParameter.addWidget(self.parm_cam_2)
        self.btnTest = QtGui.QToolButton(self.groupBox)
        self.btnTest.setGeometry(QtCore.QRect(210, 70, 41, 91))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Ubuntu"))
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.btnTest.setFont(font)
        icon8 = QtGui.QIcon()
        icon8.addPixmap(QtGui.QPixmap(_fromUtf8("ICONS/test icon.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btnTest.setIcon(icon8)
        self.btnTest.setIconSize(QtCore.QSize(54, 54))
        self.btnTest.setCheckable(True)
        self.btnTest.setAutoExclusive(False)
        self.btnTest.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.btnTest.setObjectName(_fromUtf8("btnTest"))
        self.hs_trigger_timeout = QtGui.QSlider(self.groupBox)
        self.hs_trigger_timeout.setGeometry(QtCore.QRect(20, 220, 171, 21))
        self.hs_trigger_timeout.setMinimum(1)
        self.hs_trigger_timeout.setMaximum(10000)
        self.hs_trigger_timeout.setProperty("value", 3200)
        self.hs_trigger_timeout.setOrientation(QtCore.Qt.Horizontal)
        self.hs_trigger_timeout.setObjectName(_fromUtf8("hs_trigger_timeout"))
        self.lb_trigger_timeout = QtGui.QLabel(self.groupBox)
        self.lb_trigger_timeout.setGeometry(QtCore.QRect(20, 260, 161, 20))
        self.lb_trigger_timeout.setText(_fromUtf8(""))
        self.lb_trigger_timeout.setObjectName(_fromUtf8("lb_trigger_timeout"))
        self.gridLayout_14.addWidget(self.groupBox, 0, 0, 1, 1)
        self.tabWidget.addTab(self.Settings, _fromUtf8(""))
        self.gridLayout_9.addWidget(self.tabWidget, 0, 0, 1, 1)
        self.gridLayout_2.addWidget(self.frame, 0, 0, 1, 1)
        self.swView = QtGui.QStackedWidget(self.centralwidget)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.swView.setFont(font)
        self.swView.setStyleSheet(_fromUtf8("QStackedWidget{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}"))
        self.swView.setObjectName(_fromUtf8("swView"))
        self.live_view = QtGui.QWidget()
        self.live_view.setObjectName(_fromUtf8("live_view"))
        self.gridLayout = QtGui.QGridLayout(self.live_view)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.gbCam_0 = QtGui.QGroupBox(self.live_view)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.gbCam_0.setFont(font)
        self.gbCam_0.setObjectName(_fromUtf8("gbCam_0"))
        self.lbCam_0 = QtGui.QLabel(self.gbCam_0)
        self.lbCam_0.setGeometry(QtCore.QRect(40, 40, 411, 301))
        self.lbCam_0.setMinimumSize(QtCore.QSize(180, 180))
        self.lbCam_0.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.lbCam_0.setFont(font)
        self.lbCam_0.setStyleSheet(_fromUtf8("QLabel{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}"))
        self.lbCam_0.setText(_fromUtf8(""))
        self.lbCam_0.setPixmap(QtGui.QPixmap(_fromUtf8("../ICONS/LOGO1.jpg")))
        self.lbCam_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCam_0.setObjectName(_fromUtf8("lbCam_0"))
        self.gbCam_1 = QtGui.QGroupBox(self.gbCam_0)
        self.gbCam_1.setGeometry(QtCore.QRect(340, 0, 561, 877))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.gbCam_1.setFont(font)
        self.gbCam_1.setTitle(_fromUtf8(""))
        self.gbCam_1.setObjectName(_fromUtf8("gbCam_1"))
        self.lbCam_1 = QtGui.QLabel(self.gbCam_1)
        self.lbCam_1.setGeometry(QtCore.QRect(140, 40, 411, 301))
        self.lbCam_1.setMinimumSize(QtCore.QSize(180, 180))
        self.lbCam_1.setMaximumSize(QtCore.QSize(640, 480))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.lbCam_1.setFont(font)
        self.lbCam_1.setStyleSheet(_fromUtf8("QLabel{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}"))
        self.lbCam_1.setText(_fromUtf8(""))
        self.lbCam_1.setPixmap(QtGui.QPixmap(_fromUtf8("../ICONS/LOGO1.jpg")))
        self.lbCam_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCam_1.setObjectName(_fromUtf8("lbCam_1"))
        self.lbres1 = QtGui.QLabel(self.gbCam_1)
        self.lbres1.setGeometry(QtCore.QRect(140, 390, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbres1.setFont(font)
        self.lbres1.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lbres1.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbres1.setText(_fromUtf8(""))
        self.lbres1.setObjectName(_fromUtf8("lbres1"))
        self.lbwarn_win = QtGui.QLabel(self.gbCam_1)
        self.lbwarn_win.setGeometry(QtCore.QRect(270, 350, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbwarn_win.setFont(font)
        self.lbwarn_win.setObjectName(_fromUtf8("lbwarn_win"))
        self.label = QtGui.QLabel(self.gbCam_1)
        self.label.setGeometry(QtCore.QRect(160, 10, 101, 17))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.lbwarn_win_2 = QtGui.QLabel(self.gbCam_1)
        self.lbwarn_win_2.setGeometry(QtCore.QRect(150, 400, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbwarn_win_2.setFont(font)
        self.lbwarn_win_2.setObjectName(_fromUtf8("lbwarn_win_2"))
        self.lbres2 = QtGui.QLabel(self.gbCam_1)
        self.lbres2.setGeometry(QtCore.QRect(140, 490, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbres2.setFont(font)
        self.lbres2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lbres2.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbres2.setText(_fromUtf8(""))
        self.lbres2.setObjectName(_fromUtf8("lbres2"))
        self.lbres3 = QtGui.QLabel(self.gbCam_1)
        self.lbres3.setGeometry(QtCore.QRect(140, 580, 411, 61))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbres3.setFont(font)
        self.lbres3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.lbres3.setFrameShadow(QtGui.QFrame.Sunken)
        self.lbres3.setText(_fromUtf8(""))
        self.lbres3.setObjectName(_fromUtf8("lbres3"))
        self.lbwarn_win_3 = QtGui.QLabel(self.gbCam_1)
        self.lbwarn_win_3.setGeometry(QtCore.QRect(150, 510, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbwarn_win_3.setFont(font)
        self.lbwarn_win_3.setObjectName(_fromUtf8("lbwarn_win_3"))
        self.lbwarn_win_4 = QtGui.QLabel(self.gbCam_1)
        self.lbwarn_win_4.setGeometry(QtCore.QRect(150, 590, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbwarn_win_4.setFont(font)
        self.lbwarn_win_4.setObjectName(_fromUtf8("lbwarn_win_4"))
        self.lbWarn1 = QtGui.QLabel(self.gbCam_1)
        self.lbWarn1.setGeometry(QtCore.QRect(320, 400, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbWarn1.setFont(font)
        self.lbWarn1.setText(_fromUtf8(""))
        self.lbWarn1.setObjectName(_fromUtf8("lbWarn1"))
        self.lbWarn2 = QtGui.QLabel(self.gbCam_1)
        self.lbWarn2.setGeometry(QtCore.QRect(320, 510, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbWarn2.setFont(font)
        self.lbWarn2.setText(_fromUtf8(""))
        self.lbWarn2.setObjectName(_fromUtf8("lbWarn2"))
        self.lbWarn3 = QtGui.QLabel(self.gbCam_1)
        self.lbWarn3.setGeometry(QtCore.QRect(320, 590, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbWarn3.setFont(font)
        self.lbWarn3.setText(_fromUtf8(""))
        self.lbWarn3.setObjectName(_fromUtf8("lbWarn3"))
        self.lbCam_2 = QtGui.QLabel(self.gbCam_0)
        self.lbCam_2.setGeometry(QtCore.QRect(40, 380, 411, 301))
        self.lbCam_2.setMinimumSize(QtCore.QSize(180, 180))
        self.lbCam_2.setMaximumSize(QtCore.QSize(640, 341))
        font = QtGui.QFont()
        font.setFamily(_fromUtf8("Times New Roman"))
        self.lbCam_2.setFont(font)
        self.lbCam_2.setStyleSheet(_fromUtf8("QLabel{\n"
"border-width: 0.5px;\n"
"border-color:rgb(213, 213, 213);\n"
"border-style: solid;\n"
"background-color:rgb(255, 255, 255);\n"
"}"))
        self.lbCam_2.setText(_fromUtf8(""))
        self.lbCam_2.setPixmap(QtGui.QPixmap(_fromUtf8("../ICONS/LOGO1.jpg")))
        self.lbCam_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lbCam_2.setObjectName(_fromUtf8("lbCam_2"))
        self.lbCam2_name = QtGui.QLabel(self.gbCam_0)
        self.lbCam2_name.setGeometry(QtCore.QRect(70, 350, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.lbCam2_name.setFont(font)
        self.lbCam2_name.setObjectName(_fromUtf8("lbCam2_name"))
        self.gridLayout.addWidget(self.gbCam_0, 0, 0, 1, 1)
        self.swView.addWidget(self.live_view)
        self.test_view = QtGui.QWidget()
        self.test_view.setObjectName(_fromUtf8("test_view"))
        self.gridLayout_15 = QtGui.QGridLayout(self.test_view)
        self.gridLayout_15.setMargin(0)
        self.gridLayout_15.setObjectName(_fromUtf8("gridLayout_15"))
        self.lb_test_0 = QtGui.QLabel(self.test_view)
        self.lb_test_0.setMinimumSize(QtCore.QSize(300, 200))
        self.lb_test_0.setMaximumSize(QtCore.QSize(300, 200))
        self.lb_test_0.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_test_0.setObjectName(_fromUtf8("lb_test_0"))
        self.gridLayout_15.addWidget(self.lb_test_0, 0, 0, 1, 1)
        self.lb_test_1 = QtGui.QLabel(self.test_view)
        self.lb_test_1.setMinimumSize(QtCore.QSize(300, 200))
        self.lb_test_1.setMaximumSize(QtCore.QSize(300, 200))
        self.lb_test_1.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_test_1.setObjectName(_fromUtf8("lb_test_1"))
        self.gridLayout_15.addWidget(self.lb_test_1, 0, 1, 1, 1)
        self.lb_test_2 = QtGui.QLabel(self.test_view)
        self.lb_test_2.setMinimumSize(QtCore.QSize(300, 200))
        self.lb_test_2.setMaximumSize(QtCore.QSize(300, 200))
        self.lb_test_2.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_test_2.setObjectName(_fromUtf8("lb_test_2"))
        self.gridLayout_15.addWidget(self.lb_test_2, 1, 0, 1, 1)
        self.lb_test_3 = QtGui.QLabel(self.test_view)
        self.lb_test_3.setMinimumSize(QtCore.QSize(300, 200))
        self.lb_test_3.setMaximumSize(QtCore.QSize(300, 200))
        self.lb_test_3.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_test_3.setObjectName(_fromUtf8("lb_test_3"))
        self.gridLayout_15.addWidget(self.lb_test_3, 1, 1, 1, 1)
        self.swView.addWidget(self.test_view)
        self.gridLayout_2.addWidget(self.swView, 0, 1, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(1)
        self.swParameter.setCurrentIndex(2)
        self.swView.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "dzine", None))
        self.gp_object_tools.setTitle(_translate("MainWindow", "Object tools", None))
        self.btn_login.setText(_translate("MainWindow", "login", None))
        self.btn_inspect.setText(_translate("MainWindow", "INSPECT", None))
        self.gp_object_specification.setTitle(_translate("MainWindow", "TOOLS", None))
        self.btnReset.setText(_translate("MainWindow", "Reset", None))
        self.btnBackup.setText(_translate("MainWindow", "Backup", None))
        self.btnReload.setText(_translate("MainWindow", "Reload", None))
        self.gp_object_specification_2.setTitle(_translate("MainWindow", "COUNT", None))
        self.lbrhs.setText(_translate("MainWindow", "RHS", None))
        self.lbmdl.setText(_translate("MainWindow", "MDL", None))
        self.lblhs.setText(_translate("MainWindow", "LHS", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Objects), _translate("MainWindow", "Objects", None))
        self.groupBox.setTitle(_translate("MainWindow", "Tools", None))
        self.gpCameraTools.setTitle(_translate("MainWindow", "Camera tools", None))
        self.btnCam_0.setText(_translate("MainWindow", "CAM0", None))
        self.btnCam_1.setText(_translate("MainWindow", "CAM1", None))
        self.btnCam_2.setText(_translate("MainWindow", "CAM2", None))
        self.lbCamSample_0.setText(_translate("MainWindow", "#", None))
        self.gpSourceTools_0.setTitle(_translate("MainWindow", "Source tools", None))
        self.btnRecord_3.setText(_translate("MainWindow", "Record", None))
        self.btnLive_3.setText(_translate("MainWindow", "Live", None))
        self.btnVideo_3.setText(_translate("MainWindow", "Video", None))
        self.gpSourceTools_1.setTitle(_translate("MainWindow", "Source tools", None))
        self.btnRecord_4.setText(_translate("MainWindow", "Record", None))
        self.btnLive_4.setText(_translate("MainWindow", "Live", None))
        self.btnVideo_4.setText(_translate("MainWindow", "Video", None))
        self.lbCamSample_1.setText(_translate("MainWindow", "#", None))
        self.lbCamSample_2.setText(_translate("MainWindow", "#", None))
        self.gpSourceTools_2.setTitle(_translate("MainWindow", "Source tools", None))
        self.btnVideo_2.setText(_translate("MainWindow", "Video", None))
        self.btnRecord_2.setText(_translate("MainWindow", "Record", None))
        self.btnLive_2.setText(_translate("MainWindow", "Live", None))
        self.btnTest.setText(_translate("MainWindow", "Test", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.Settings), _translate("MainWindow", "Settings", None))
        self.gbCam_0.setTitle(_translate("MainWindow", "                 CAM --> RHS", None))
        self.lbwarn_win.setText(_translate("MainWindow", "Result Window", None))
        self.label.setText(_translate("MainWindow", "CAM --> MID", None))
        self.lbwarn_win_2.setText(_translate("MainWindow", "RHS_CAM RESULT :", None))
        self.lbwarn_win_3.setText(_translate("MainWindow", "MDL_CAM RESULT :", None))
        self.lbwarn_win_4.setText(_translate("MainWindow", "LHS_CAM RESULT :", None))
        self.lbCam2_name.setText(_translate("MainWindow", "CAM --> LHS", None))
        self.lb_test_0.setText(_translate("MainWindow", "img_0", None))
        self.lb_test_1.setText(_translate("MainWindow", "img_1", None))
        self.lb_test_2.setText(_translate("MainWindow", "img_2", None))
        self.lb_test_3.setText(_translate("MainWindow", "data", None))


if __name__ == "__main__":
    import sys
    app = QtGui.QApplication(sys.argv)
    MainWindow = QtGui.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

